var time = 0;
var color = "";
function setText() {
setInterval(function setText1() {
color = "H";
color = color.fontcolor("red");
document.getElementById("text").innerHTML = color;
color = "HA";
color = color.fontcolor("orange");
if (time >= 1) {
    document.getElementById("text").innerHTML = color;
    color = "HAP";
    color = color.fontcolor("yellow");
}
if (time >= 2) {
    document.getElementById("text").innerHTML = color;
    color = "HAPP";
    color = color.fontcolor("green");
}if (time >= 3) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY";
    color = color.fontcolor("blue");
}if (time >= 4) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>M";
    color = color.fontcolor("indigo");
}if (time >= 5) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MO";
    color = color.fontcolor("violet");
}if (time >= 6) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOT";
    color = color.fontcolor("red");
}if (time >= 7) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTH";
    color = color.fontcolor("orange");
}if (time >= 8) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHE";
    color = color.fontcolor("yellow");
}if (time >= 9) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER";
    color = color.fontcolor("green");
}if (time >= 10) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'";
    color = color.fontcolor("blue");
}if (time >= 11) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S";
    color = color.fontcolor("indigo");
}if (time >= 12) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>D";
    color = color.fontcolor("violet");
}if (time >= 13) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DA";
    color = color.fontcolor("red");
}if (time >= 14) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY";
    color = color.fontcolor("orange");
}if (time >= 15) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY!";
    color = color.fontcolor("yellow");
}if (time >= 16) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY!";
    color = color.fontcolor("green");
}
if (time >= 17) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY!";
    color = color.fontcolor("blue");
}if (time >= 18) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY!";
    color = color.fontcolor("indigo");
}if (time >= 19) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY!";
    color = color.fontcolor("violet");
}if (time >= 20) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY!";
    color = color.fontcolor("red");
}if (time >= 21) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY!";
    color = color.fontcolor("orange");
}if (time >= 22) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY!";
    color = color.fontcolor("yellow");
}
if (time >= 23) {
    document.getElementById("text").innerHTML = color;
    color = "HAPPY<br>MOTHER'S<br>DAY!";
    color = color.fontcolor("yellow");
    time = 16;
}
time += 1;
}, 500)
}